version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
      - image: redis:6-alpine
        name: redis
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            python -m pip install poetry
            poetry install
      - run:
          name: Wait for Redis to be ready
          command: |
            until nc -z redis 6379; do
              echo "Waiting for Redis...";
              sleep 1;
            done
      - run:
          name: Lint
          command: |
            poetry run ruff check .
            poetry run ruff format --check .
            poetry run mypy redishilok
      - run:
          name: Run tests
          environment:
            REDIS_URL: redis://redis:6379
          command: |
            poetry run pytest -n 3 tests/ --cov=redishilok --cov-report=html --cov-fail-under=99
      - store_artifacts:
          path: htmlcov/
          destination: coverage_report

workflows:
  build-and-test:
    jobs:
      - build
