version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    services:
      redis:
        image: redis:6-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            poetry install
      - run:
          name: Wait for Redis to be ready
          command: |
            until nc -z redis 6379; do
              echo "Waiting for Redis...";
              sleep 1;
            done
      - run:
          name: Lint
          command: |
            ruff check .
            ruff format --check .
            mypy redishilok
      - run:
          name: Run tests
          command: |
            pytest -n 3 tests/ --cov=redishilok --cov-report=html --cov-fail-under=99
      - store_artifacts:
          path: htmlcov/
          destination: coverage_report

workflows:
  build-and-test:
    jobs:
      - build
